# Generated by Django 3.1.4 on 2021-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.ManyToManyField(to='crud.City'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='resources',
            field=models.ManyToManyField(to='crud.Resources'),
        ),
    ]
