# Generated by Django 3.1.4 on 2021-05-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210514_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('helpful', 'helpful'), ('unresposive', 'unresponsive'), ('wrong', 'wrong'), ('fraud', 'fraud'), ('unvarified', 'unvarified')], max_length=200, null=True),
        ),
    ]
