# Generated by Django 3.1.4 on 2021-05-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210514_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
