# Generated by Django 3.1.4 on 2021-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20210515_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('helpful', 'helpful'), ('unresponsive', 'unresponsive'), ('wrong', 'wrong'), ('fraud', 'fraud'), ('unvarified', 'unvarified')], max_length=200, null=True),
        ),
    ]
