# Generated by Django 3.1.4 on 2021-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20210516_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(default='hello', max_length=300),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, default='m60448@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Number',
            field=models.IntegerField(default=2312, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
