# Generated by Django 3.1.4 on 2021-05-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20210516_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('helpful', 'helpful'), ('unresponsive', 'unresponsive'), ('out of stock', 'out of stock'), ('wrong', 'wrong'), ('fraud', 'fraud'), ('unvarified', 'unvarified')], max_length=200, null=True),
        ),
    ]
